# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
    api:
        image: api
        build:
            context: .
            dockerfile: api/api/Dockerfile
        ports:
            - 5000
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5000
        volumes:
            - ~/.vsdbg:/remote_debugger:rw
    admin:
        image: admin
        build: .
        environment:
        NODE_ENV: development
        ports:
            - 3000
            - 9229:9229
        ## set your startup file here
        command: node --inspect=0.0.0.0:9229 index.js
