# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: "3.4"

services:
    api:
        image: api
        build:
            context: .
            dockerfile: api/api/Dockerfile
        ports:
            - 5000
    admin:
        image: admin
        build: .
        environment:
            NODE_ENV: production
        ports:
            - 3000
